"""add summary field to books table

Revision ID: 238bcefab8c3
Revises: 85242b1a76fb
Create Date: 2025-10-18 18:25:00.445363

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "238bcefab8c3"
down_revision: str | None = "85242b1a76fb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
