"""add cover_image field to books table

Revision ID: 61bf77348251
Revises: 238bcefab8c3
Create Date: 2025-10-19 11:47:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61bf77348251"
down_revision: str | None = "238bcefab8c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add cover_image column to books table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("cover_image", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove cover_image column from books table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "cover_image")
    # ### end Alembic commands ###
