"""Add title and author indexes to books table

Revision ID: 85242b1a76fb
Revises:
Create Date: 2025-09-04 13:07:53.646033

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85242b1a76fb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_books_author", "books", ["authors_text"], unique=False)
    op.create_index("ix_books_title", "books", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_books_title", table_name="books")
    op.drop_index("ix_books_author", table_name="books")
    # ### end Alembic commands ###
